/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String[] tabuleiro = new String[10];
        Scanner scanner = new Scanner(System.in);
        int i = 0;

        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            tabuleiro[i] = linha;
            i++;
        }

        if (get_tamanho_tabuleiro(tabuleiro, i)) {
            System.out.println("Tabuleiro com tamanho correto.");
        } else {
            System.out.println("Tabuleiro com tamanho incorreto.");
        }

        // System.out.println("Dados armazenados:");
        // for (String linha : tabuleiro) {
        //     System.out.println(linha);
        // }

        scanner.close();
    }

    public static boolean get_tamanho_tabuleiro(String[] tabuleiro, int i) {
        boolean tamanho_vertical_correto = (i == 10);
        boolean tamanho_horizontal_correto = true;

        for (String linha : tabuleiro) {
            if (linha == null || linha.length() != 10) {
                tamanho_horizontal_correto = false;
                break;
            }
        }

        return tamanho_vertical_correto && tamanho_horizontal_correto;
    }

    // public static boolean get_navios(String[] tabuleiro) {
        
    // }

    // public static boolean get_multiplos_navios(String[] tabuleiro) {
        
    // }
}