/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String[] tabuleiro = new String[10];
        Scanner scanner = new Scanner(System.in);
        int i = 0;

        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            tabuleiro[i] = linha;
            i++;
        }

        if (get_tamanho_tabuleiro(tabuleiro, i) && get_navios_conhecidos(tabuleiro)) {
            System.out.println("Tabuleiro válido");
        } else {
            System.out.println("Tabuleiro inválido");
        }

        // System.out.println("Dados armazenados:");
        // for (String linha : tabuleiro) {
        //     System.out.println(linha);
        // }

        scanner.close();
    }

    public static boolean get_tamanho_tabuleiro(String[] tabuleiro, int i) {
        boolean tamanho_vertical_correto = (i == 10);
        boolean tamanho_horizontal_correto = true;

        for (String linha : tabuleiro) {
            if (linha == null || linha.length() != 10) {
                tamanho_horizontal_correto = false;
                break;
            }
        }

        return tamanho_vertical_correto && tamanho_horizontal_correto;
    }

    public static boolean get_navios_conhecidos(String[] tabuleiro) {
        boolean barco_conhecidos = true;

        for (String linha : tabuleiro) {

            for (int i = 0; i < linha.length(); i++) {
                char caractere = linha.charAt(i);

                if (caractere != '.' && caractere != 'P' && caractere != 'E' && caractere != 'C' && caractere != 'S' && caractere != 'N') {
                    barco_conhecidos = false;
                    break;
                }
            }

        }
        return barco_conhecidos;
    }

    // public static boolean get_multiplos_navios(String[] tabuleiro) {
        
    // }
}