/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String[] tabuleiro = new String[10];
        Scanner scanner = new Scanner(System.in);
        int i = 0;

        while (scanner.hasNextLine()) {
            String linha = scanner.nextLine();
            dados[i] = linha;
            i++;
        }
        

        System.out.println("Dados armazenados:");
        for (String linha : tabuleiro) {
            System.out.println(linha);
        }
    }

    public static boolean get_tamanho_tabuleiro(String[] tabuleiro) {
        
    }

    public static boolean get_navios(String[] tabuleiro) {
        
    }

    public static boolean get_multiplos_navios(String[] tabuleiro) {
        
    }
}